In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
linear_regression = LinearRegression()

In [2]:
df = pd.read_csv('Registered_Libertarian_Voters_SD.csv')
pd.set_option('display.max_columns', None)
columns_to_drop = ['Walking_List_Sequence', 'LALVOTERID', 'LALVOTERID', 'Residence_Families_FamilyID', 'Mailing_Families_FamilyID', 'VoterTelephones_FullPhone', 'Telephones_Phone10', 'VoterTelephones_TelCellFlag', 'View_Ops_CellPhone_Phone10', 'View_Ops_CellPhone_FullPhone', 'Residence_Addresses_AddressLine', 'Residence_Addresses_ExtraAddressLine', 'Residence_Addresses_State', 'Residence_Addresses_Zip', 'Residence_Addresses_ZipPlus4', 'Mailing_Addresses_AddressLine', 'Mailing_Addresses_ExtraAddressLine', 'Mailing_Addresses_City', 'Mailing_Addresses_State', 'Mailing_Addresses_Zip', 'Mailing_Addresses_ZipPlus4', 'Voters_BirthDate']
df.drop(columns = columns_to_drop, inplace = True)
pd.set_option('display.max_columns', None)
df.fillna(value = 0, inplace = True)
df.replace(to_replace = 'Y', value = 1, inplace = True)
df.rename(columns = {'General_2012-11-06': 'General_2012', 'General_2014-11-04': 'General_2014', 'General_2016-11-08': 'General_2016', 'General_2018-11-06': 'General_2018'}, inplace = True)


C:\Users\Jason\Downloads\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
#df['General_2018'] = df['General_2018'].replace([1], 4)
#df['General_2016'] = df['General_2016'].replace([1], 3)
#df['General_2014'] = df['General_2014'].replace([1], 2)
df

Voters_StateVoterID Voters_Active Voters_FirstName Voters_MiddleName  \
0                  6849349        Active            Stacy                 M   
1                  6908005        Active          Michael                 A   
2                 23365115      Inactive          Madalyn                 0   
3                 30570022      Inactive          Rosalie                 0   
4                 30660866        Active       Franchesca                 0   
...                    ...           ...              ...               ...   
17339             35989813        Active          Tristan                 T   
17340             35722530        Active             Cory                 J   
17341             34212683        Active             Juan           Antonio   
17342             34836193        Active         Michaela                 L   
17343             32924360        Active             Evin                 R   

      Voters_LastName Residence_Addresses_City Voters_CalculatedRegDate  \
0           Achenbach                   Alpine                9/27/1995   
1              Aitken                   Alpine                 5/3/1998   
2             Arevalo                   Alpine                 4/7/2015   
3             Arevalo                   Alpine                 8/8/2016   
4            Barisano                   Alpine                 2/1/2018   
...               ...                      ...                      ...   
17339        McMillin             San Clemente               12/18/2019   
17340           Nagel             San Clemente               10/11/2019   
17341          Picazo             San Clemente                2/17/2020   
17342         Summers             San Clemente                10/7/2018   
17343          Watson             San Clemente                3/16/2019   

       Voters_Age Parties_Description Voters_Gender  \
0            57.0         Libertarian             F   
1            53.0         Libertarian             M   
2            24.0         Libertarian             F   
3            22.0         Libertarian             F   
4            38.0         Libertarian             F   
...           ...                 ...           ...   
17339        22.0         Libertarian             M   
17340        23.0         Libertarian             M   
17341        37.0         Libertarian             M   
17342        24.0         Libertarian             F   
17343        21.0         Libertarian             0   

      EthnicGroups_EthnicGroup1Desc  2011_NEW_Congressional_District  \
0                          European                             50.0   
1                          European                             50.0   
2           Hispanic and Portuguese                             50.0   
3           Hispanic and Portuguese                             50.0   
4                          European                             50.0   
...                             ...                              ...   
17339                      European                             49.0   
17340                      European                             49.0   
17341       Hispanic and Portuguese                             49.0   
17342                      European                             49.0   
17343                      European                             49.0   

       2011_NEW_State_Senate_District  2011_NEW_State_House_District  \
0                                38.0                           71.0   
1                                38.0                           71.0   
2                                38.0                           71.0   
3                                38.0                           71.0   
4                                38.0                           71.0   
...                               ...                            ...   
17339                            36.0                           76.0   
17340                            36.0                  

In [4]:
df['Primary_2016-06-07'].value_counts()

0    13525
1     3819
Name: Primary_2016-06-07, dtype: int64

In [5]:
df['General_2016'].value_counts()

1    9645
0    7699
Name: General_2016, dtype: int64

In [6]:
X = df[['General_2012', 'General_2014', 'Presidential_Primary_2012-06-05', 'Primary_2014-06-03', 'Presidential_Primary_2016-06-07']]

In [7]:
y = df['General_2016']

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=66)

# Multiple Linear Regression Section

In [9]:
linear_regression.fit(X_train,y_train)
y_pred = linear_regression.predict([[0, 1, 0, 1, 1,]])
y_pred
# needs to be better, I don't think this is very accurate. Perhpaps we should weight the voting instances based on the proportion of total 'Y's or '1's that are associated with it, or use another model.

array([0.78358007])

# Random Forests Section

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Split into Training and Testing Data

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=66)

# Setup Model

In [12]:
#X_test, y_test = make_classification(n_samples=17339, n_features=5,
                        #n_informative=2, n_redundant=0,
                        #random_state=0, shuffle=False)
clf = RandomForestClassifier(max_depth=2, random_state=0, class_weight = "balanced")
clf.fit(X_train, y_train)


C:\Users\Jason\Downloads\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=10, n_jobs=None, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)

In [13]:
clf.apply(X_train)

array([[6, 6, 6, ..., 6, 6, 6],
       [6, 3, 6, ..., 6, 6, 5],
       [3, 2, 2, ..., 3, 5, 5],
       ...,
       [3, 2, 2, ..., 3, 5, 5],
       [2, 3, 3, ..., 2, 3, 3],
       [2, 2, 2, ..., 2, 2, 2]], dtype=int32)

In [14]:
clf.decision_path(X_train)

(<11620x70 sparse matrix of type '<class 'numpy.intc'>'
 	with 348600 stored elements in Compressed Sparse Row format>,
 array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70], dtype=int32))

In [15]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight='balanced',
                       criterion='gini', max_depth=2, max_features='auto',
                       max_leaf_nodes=None, min_impurity_decrease=0.0,
                       min_impurity_split=None, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       n_estimators=10, n_jobs=None, oob_score=False,
                       random_state=0, verbose=0, warm_start=False)

# THIS IS THE RESULT

In [25]:
clf.predict_proba([[0,1,0,1,1]])

array([[0.11504577, 0.88495423]])

# Importance of Features

In [17]:
clf.feature_importances_

array([0.30468545, 0.30676526, 0.06183981, 0.00940054, 0.31730893])

# Evaluate Model

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix

In [19]:
clf_cv_score = cross_val_score(clf, X, y, cv=10)

In [20]:
#print(confusion_matrix(y_test, clf_predict))
#print(classification_report(y_test, clf_predict))
#print(clf_cv_score)
#print(clf_cv_score.mean)

In [21]:
clf.score(X_train, y_train)

0.7574010327022376